import type {Metadata} from "next";
import {Karla} from "next/font/google";
import "./globals.css";

const karlaFont = Karla({
	display: "swap",
	subsets: ["latin"],
	style: ["normal", "italic"],
	weight: ["200", "300", "400", "500", "700", "800"],
});

export const metadata: Metadata = {
	title: "Contact Form",
	description: "Generated by create next app",
};

const RootLayout = ({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) => {
	return (
		<html lang="en">
			<body className={`${karlaFont.className}`}>{children}</body>
		</html>
	);
};

export default RootLayout;
